### ISSUE TITLE
Check failed error!

### ISSUE THREAD

**Issue by pengpaiSH** [pertusa/MXNetToCaffeConverter#4]
When I am using this tool, I ran into a checking failure error. However, I was able to successfully get the converted Caffe model. Does it matter?  Thank you for your attention!

![image](https://cloud.githubusercontent.com/assets/3724085/21342258/02947528-c6cc-11e6-979d-b2fb04a2b0c7.png)

**Comment by pertusa** [comment]
With these errors, the output weights may be written, but they will be wrong. The first means that a layer name was not found in the MXNet JSON file, and the second that the original layer size is different than the output size (because of the first error).

For example, in the Inception21k original model at http://data.dmlc.ml/mxnet/models/imagenet/inception-21k.tar.gz look at the file "Inception-symbol.json". MXNet layers in the JSON file should have a suffix (such as “_weight”, “_bias”, “_gamma”, etc), as  You can see at the file mxnet_to_caffe.cpp that, for example, MXNet fully connected and convolutional layer names are assumed to have their corresponding suffixes "_weight" and "_bias”.

**Comment by pengpaiSH** [comment]
@pertusa Really appreciate that your feedback. With that said, you are suggestion that I should modify my own JSON file (MXNet model definition) so that each layer has a proper suffix, e.g. "_weight", right?

**Comment by pertusa** [comment]
Right, this would be an example of a convolutional layer:

    {
      "op": "null",
      "param": {},
      "name": "conv_conv1_weight",
      "inputs": [],
      "backward_source_id": -1
    },
    {
      "op": "null",
      "param": {},
      "name": "conv_conv1_bias",
      "inputs": [],
      "backward_source_id": -1
    },
    {
      "op": "Convolution",
      "param": {
        "kernel": "(7, 7)",
        "no_bias": "False",
        "num_filter": "96",
        "num_group": "1",
        "pad": "(3, 3)",
        "stride": "(2, 2)",
        "workspace": "512"
      },
      "name": "conv_conv1",
      "inputs": [[0, 0], [1, 0], [2, 0]],
      "backward_source_id": -1
    }

**Comment by pengpaiSH** [comment]
Thank you @pertusa . How about the prototxt for Caffe? Does each layer name should correspond to each other?

**Comment by pengpaiSH** [comment]
@pertusa BTW, I have checked my JSON file it indeed has the proper suffix. And I have saved the log. Note that my JSON file is a squeeze [network.](http://data.dmlc.ml/models/imagenet/squeezenet/squeezenet_v1.0-symbol.json) Could you please have a look for me?
```
Ignoring layer data
Ignoring layer label_data_1_split
Dumping ConvolutionLayer conv1
Ignoring layer relu_conv1
Ignoring layer pool1
Dumping ConvolutionLayer fire2/squeeze1x1
Ignoring layer fire2/relu_squeeze1x1
Ignoring layer fire2/squeeze1x1_fire2/relu_squeeze1x1_0_split
Dumping ConvolutionLayer fire2/expand1x1
Ignoring layer fire2/relu_expand1x1
Dumping ConvolutionLayer fire2/expand3x3
Ignoring layer fire2/relu_expand3x3
Ignoring layer fire2/concat
Dumping ConvolutionLayer fire3/squeeze1x1
Ignoring layer fire3/relu_squeeze1x1
Ignoring layer fire3/squeeze1x1_fire3/relu_squeeze1x1_0_split
Dumping ConvolutionLayer fire3/expand1x1
Ignoring layer fire3/relu_expand1x1
Dumping ConvolutionLayer fire3/expand3x3
Ignoring layer fire3/relu_expand3x3
Ignoring layer fire3/concat
```

**Comment by pengpaiSH** [comment]
![image](https://cloud.githubusercontent.com/assets/3724085/21417555/5e415f22-c856-11e6-9b43-ebd52ef7fe40.png)
It seems that only convolutional layers are successfully converted?

**Comment by pertusa** [comment]
The "Ignoring layer" message is not a problem. Concat, pooling and activation layers (such as RELU) never contain stored weights therefore they do not need to be converted and are ignored.

About the question "Does each layer name should correspond to each other?", yes, the prototxt layers should have the same name than in JSON, this is how weights are mapped from one network to the other. The "Check failed" errors may be due to these inconsistencies.

**Comment by pengpaiSH** [comment]
@pertusa Really thank you for your reply. It helps a lot!

**Comment by pengpaiSH** [comment]
@pertusa Pertusa, I am converting a SqueezeNet_v1.1 MXNet model to a Caffe model using this tool. And I confirm that these layer names correspond to each other except that the JSON file contains a "flatten" layer while Caffe prototxt file does not (with a global averaging layer). Would you please take a look for me? Thank you!

[tmp.zip](https://github.com/pertusa/MXNetToCaffeConverter/files/670646/tmp.zip)
